name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Backend
      - name: Build backend image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:latest ./backend

      - name: Push backend image
        run: |
          docker push ghcr.io/${{ github.repository }}/backend:latest

      # Frontend
      - name: Build frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:latest ./frontend

      - name: Push frontend image
        run: |
          docker push ghcr.io/${{ github.repository }}/frontend:latest
